Repository Arique1104/viewing_party, pull requests merged in 2020-10, with the labels that each got.

#19 Template test
  JOINTBRAINSTORM.md
  README.md
Labels: Replied to Comments/Questions, Reviewed, chore, merges to main

#21 Welcome page
  app/controllers/welcome_controller.rb
  app/views/welcome/index.html.erb
  config/routes.rb
  spec/features/welcome/welcome_spec.rb
Labels: chore, merges to main

#22 User
  Gemfile
  Gemfile.lock
  app/models/user.rb
  db/migrate/20201007195608_create_users.rb
  db/schema.rb
  spec/models/user_spec.rb
  spec/rails_helper.rb
Labels: Core, Reviewed

#23 Database friendships
  app/models/friendship.rb
  app/models/user.rb
  brainstorm.md
  db/migrate/20201007213153_create_friendships.rb
  db/schema.rb
  spec/models/friendship_spec.rb
  spec/models/user_spec.rb
Labels: Core

#24 Figaro
  .gitignore
  Gemfile
  Gemfile.lock
  app/controllers/welcome_controller.rb
Labels: Core, Reviewed, merges to main

#27 Registration
  app/controllers/users_controller.rb
  app/models/user.rb
  app/views/users/new.html.erb
  app/views/users/show.html.erb
  app/views/welcome/index.html.erb
  config/routes.rb
  spec/features/registration/registration_spec.rb
Labels: Core, Response from Author - see eyes, Reviewed

#25 Add Party database and joins for party_participants
  app/models/friendship.rb
  app/models/party.rb
  app/models/party_participant.rb
  db/migrate/20201009174046_create_parties.rb
  db/migrate/20201009180036_create_party_participants.rb
  db/schema.rb
  spec/models/friendship_spec.rb
  spec/models/party_participant_spec.rb
  spec/models/party_spec.rb
Labels: Core

#29 SUBJECT: Update Readme
  README.md
Labels: documentation

#30 Dashboard
  app/controllers/application_controller.rb
  app/controllers/users_controller.rb
  app/models/user.rb
  app/views/users/show.html.erb
  spec/features/dashboard/dashboard_spec.rb
Labels: Core, Review me FIRST

#33 Discover search ii
  app/controllers/movie_controller.rb
  app/views/discover/show.html.erb
  app/views/movie/search.html.erb
  app/views/movie/top_forty.html.erb
  config/routes.rb
  spec/features/movies/search_by_movie_title_spec.rb
  spec/fixtures/top_forty_results.json
Labels: API consumption, Core

#34 SUBJECT: Update models in paired session as needed
  app/models/friendship.rb
  app/models/party.rb
  app/models/party_participant.rb
  app/models/user.rb
  db/migrate/20201013141331_create_users.rb
  db/migrate/20201013141617_create_friendships.rb
  db/migrate/20201013141957_create_parties.rb
  db/migrate/20201013142043_create_party_participants.rb
  db/schema.rb
  spec/features/dashboard/dashboard_spec.rb
  spec/features/registration/registration_spec.rb
  spec/features/welcome/welcome_spec.rb
  spec/models/friendship_spec.rb
  spec/models/party_participant_spec.rb
  spec/models/party_spec.rb
  spec/models/user_spec.rb
Labels: chore, peer coded

#35 Dashboard friends
  app/controllers/discover_controller.rb
  app/controllers/users_controller.rb
  app/models/user.rb
  app/views/discover/show.html.erb
  app/views/users/new.html.erb
  app/views/users/show.html.erb
  config/routes.rb
  spec/features/dashboard/dashboard_spec.rb
  spec/features/movies/search_by_movie_title_spec.rb
  spec/features/registration/registration_spec.rb
  spec/features/welcome/welcome_spec.rb
  spec/models/user_spec.rb
Labels: ActiveRecord, Core

#36 Api refactor
  app/controllers/movie_controller.rb
  app/facades/movie_facade.rb
  app/poros/movie.rb
  app/services/movie_service.rb
  app/views/movie/search.html.erb
  app/views/movie/top_forty.html.erb
  spec/poros/movie_spec.rb
  spec/services/movie_service_spec.rb
  spec/spec_helper.rb
Labels: merges to main, refactor

#37 Movie details
  app/controllers/movie_controller.rb
  app/controllers/users_controller.rb
  app/facades/movie_facade.rb
  app/models/user.rb
  app/poros/cast_member.rb
  app/poros/movie_details.rb
  app/poros/movie_review.rb
  app/services/movie_service.rb
  app/views/movie/show.html.erb
  config/routes.rb
  spec/features/movies/show_spec.rb
  spec/poros/cast_member_spec.rb
  spec/poros/movie_details_spec.rb
  spec/poros/movie_review_spec.rb
  spec/poros/movie_spec.rb
Labels: API consumption, Core, Reviewed, merges to main

#38 Viewing party
  app/controllers/parties_controller.rb
  app/controllers/users_controller.rb
  app/models/party.rb
  app/poros/movie_details.rb
  app/poros/schedule.rb
  app/views/discover/show.html.erb
  app/views/movie/show.html.erb
  app/views/parties/new.html.erb
  app/views/users/show.html.erb
  config/routes.rb
  db/migrate/20201015002602_add_movie_title_to_parties.rb
  db/migrate/20201015005006_remove_movie_id_from_parties.rb
  db/schema.rb
  db/seeds.rb
  spec/features/party/new_spec.rb
  spec/features/users/dashboard_show_spec.rb
  spec/models/party_spec.rb
  spec/poros/movie_details_spec.rb
  spec/poros/schedule_spec.rb
Labels: Core

#39 Dashboard viewing party
  app/controllers/parties_controller.rb
  app/views/users/show.html.erb
  spec/features/party/new_spec.rb
  spec/features/users/dashboard_show_spec.rb
Labels: Core, Review me FIRST

#40 Priya refactor attempt
  app/controllers/movie_controller.rb
  app/controllers/parties_controller.rb
  app/models/friendship.rb
  app/services/movie_service.rb
  app/views/discover/show.html.erb
  app/views/movie/index.html.erb
  app/views/movie/search.html.erb
  app/views/parties/new.html.erb
  config/routes.rb
  spec/features/movies/index_spec.rb
  spec/features/party/new_spec.rb
Labels: refactor

#41 SUBJECT: Update application for ability to log out
  app/controllers/sessions_controller.rb
  config/routes.rb
  spec/features/users/logout_spec.rb
Labels: chore

#43 SUBJECT: Debug API calls to return two separate pages
  app/services/movie_service.rb
Labels: bug, chore, merges to main

#44 Party Creation Bug
  app/controllers/parties_controller.rb
Labels: bug, merges to main

#45 Fixes bug
  app/controllers/parties_controller.rb
  app/views/parties/new.html.erb
  spec/features/welcome/welcome_spec.rb
Labels: bug, merges to main
